const initialState = {
    
    upgrades: [
    
        { galaxyId:'galaxy0', id:'galaxy0upgrade0',   cost:2.5e+5,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade1',   cost:5e+5,      count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade2',   cost:1e+6,      count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade3',   cost:5e+6,      count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade4',   cost:1e+7,      count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade5',   cost:2.5e+7,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade6',   cost:5e+8,      count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade7',   cost:1e+10,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade8',   cost:5e+10,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade9',   cost:2.5e+11,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade10',  cost:1e+12,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade11',  cost:2e+13,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade12',  cost:5e+13,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade13',  cost:1e+14,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade14',  cost:5e+14,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade15',  cost:1e+15,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade16',  cost:2e+15,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade17',  cost:5e+15,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade18',  cost:7e+15,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade19',  cost:1e+16,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade20',  cost:2e+16,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade21',  cost:5e+16,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade22',  cost:1e+17,     count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:1 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade23',  cost:2e+18,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade24',  cost:5e+18,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade25',  cost:7e+18,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade26',  cost:1e+19,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade27',  cost:2e+19,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade28',  cost:3.5e+19,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade29',  cost:5e+19,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade30',  cost:7.5e+19,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade31',  cost:1e+20,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade32',  cost:2e+20,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade33',  cost:5e+20,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade34',  cost:1e+21,     count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:1 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade35',  cost:2.5e+22,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade36',  cost:5e+22,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade37',  cost:1e+23,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade38',  cost:2e+23,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade39',  cost:3e+23,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade40',  cost:4e+23,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade41',  cost:5e+23,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade42',  cost:6e+23,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade43',  cost:7e+23,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade44',  cost:8e+23,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade45',  cost:9e+23,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade46',  cost:1e+25,     count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade47',  cost:1e+27,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade48',  cost:5e+27,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade49',  cost:2.5e+28,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade50',  cost:1e+29,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade51',  cost:2.5e+29,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade52',  cost:5e+29,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade53',  cost:1e+30,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade54',  cost:5e+30,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade55',  cost:2.5e+31,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade56',  cost:5e+31,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade57',  cost:1e+42,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade58',  cost:5e+42,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade59',  cost:2.5e+43,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade60',  cost:5e+43,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade61',  cost:1e+44,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade62',  cost:2.5e+44,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade63',  cost:5e+44,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade64',  cost:1e+45,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade65',  cost:5e+45,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade66',  cost:1e+46,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade67',  cost:2.5e+46,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade68',  cost:1e+47,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade69',  cost:2.5e+47,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade70',  cost:5e+47,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade71',  cost:7.5e+47,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade72',  cost:1e+48,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade73',  cost:5e+48,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade74',  cost:1.5e+49,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade75',  cost:5e+49,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade76',  cost:1e+50,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade77',  cost:2.5e+50,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade78',  cost:5e+50,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade79',  cost:1e+51,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade80',  cost:1e+54,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade81',  cost:1e+60,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade82',  cost:1e+61,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade83',  cost:1e+62,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade84',  cost:1e+66,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade85',  cost:1e+67,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade86',  cost:1e+68,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade87',  cost:1e+72,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:11 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade88',  cost:1e+73,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade89',  cost:1e+74,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade90',  cost:1e+75,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:13 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade91',  cost:1e+76,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade92',  cost:1e+77,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade93',  cost:1e+78,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:15 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade94',  cost:1e+79,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade95',  cost:1e+80,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade96',  cost:1e+84,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade97',  cost:3e+87,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3.1415926 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade98',  cost:1e+90,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade99',  cost:5e+90,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade100', cost:2.5e+91,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade101', cost:5e+91,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade102', cost:1e+92,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade103', cost:2.5e+92,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade104', cost:5e+92,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade105', cost:1e+93,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade106', cost:5e+93,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade107', cost:1e+94,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade108', cost:5e+95,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade109', cost:2e+96,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade110', cost:1.1e+97,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade111', cost:6.6e+97,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade112', cost:2.3e+98,   count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade113', cost:4e+98,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade114', cost:7e+98,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade115', cost:4e+99,     count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade116', cost:1e+100,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade117', cost:2e+100,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:6 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade118', cost:2.9e+100,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade119', cost:1.45e+101, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade120', cost:3e+101,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade121', cost:5e+101,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade122', cost:1e+102,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade123', cost:5e+102,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade124', cost:1.5e+104,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade125', cost:4e+104,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade126', cost:9e+104,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade127', cost:6e+105,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade128', cost:1.5e+106,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade129', cost:6e+106,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade130', cost:1.85e+107, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade131', cost:5e+107,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade132', cost:6e+107,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade133', cost:7.5e+107,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade134', cost:5e+108,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade135', cost:4.5e+109,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade136', cost:1.25e+110, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade137', cost:3e+110,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade138', cost:9e+110,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade139', cost:1e+111,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade140', cost:5e+111,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade141', cost:7e+112,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade142', cost:2.5e+113,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade143', cost:5e+113,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade144', cost:9e+113,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade145', cost:3e+114,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade146', cost:1.5e+115,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade147', cost:7.5e+115,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade148', cost:4e+116,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade149', cost:4.5e+116,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade150', cost:5e+116,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade151', cost:7.5e+116,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade152', cost:1e+117,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade153', cost:2e+117,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade154', cost:2e+118,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade155', cost:1.5e+119,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade156', cost:3.5e+119,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade157', cost:5e+119,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade158', cost:7e+119,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade159', cost:9.5e+119,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade160', cost:4e+120,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade161', cost:9e+120,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade162', cost:2.4e+121,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade163', cost:1.11e+122, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade164', cost:2.22e+122, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade165', cost:3.33e+122, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade166', cost:4.44e+122, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade167', cost:5.55e+122, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade168', cost:6.66e+122, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:6.66 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade169', cost:1e+123,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade170', cost:3e+123,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade171', cost:6e+123,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade172', cost:1.2e+124,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade173', cost:2.4e+124,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade174', cost:4.8e+124,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade175', cost:9.6e+124,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade176', cost:1.92e+125, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade177', cost:3.84e+125, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade178', cost:7.68e+125, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade179', cost:1e+126,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade180', cost:1e+127,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade181', cost:2e+129,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade182', cost:5e+129,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade183', cost:1.3e+130,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade184', cost:2.9e+130,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade185', cost:7.1e+130,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade186', cost:1.77e+131, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade187', cost:2.5e+131,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade188', cost:3.1e+131,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade189', cost:5.55e+131, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade190', cost:7.36e+131, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade191', cost:9e+131,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade192', cost:5e+132,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade193', cost:9.5e+133,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade194', cost:2.13e+134, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade195', cost:4e+134,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade196', cost:9.85e+134, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade197', cost:8e+135,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade198', cost:2.9e+136,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade199', cost:2.22e+137, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade200', cost:5e+137,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade201', cost:9e+137,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade202', cost:5e+138,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade203', cost:1.36e+140, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade204', cost:7e+140,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade205', cost:9.25e+140, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade206', cost:3e+141,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade207', cost:2.1e+142,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade208', cost:5.5e+142,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade209', cost:1.11e+143, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade210', cost:2.23e+143, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade211', cost:3.93e+143, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade212', cost:6e+143,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade213', cost:7.99e+143, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade214', cost:2e+144,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade215', cost:3e+144,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade216', cost:6e+144,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade217', cost:9e+144,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade218', cost:2.1e+145,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade219', cost:4.4e+145,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade220', cost:8.9e+145,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade221', cost:1.29e+146, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade222', cost:1.8e+146,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade223', cost:2.1e+146,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade224', cost:3e+146,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade225', cost:4.5e+146,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2.71828 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade226', cost:5e+147,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade227', cost:3e+148,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade228', cost:1.8e+149,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade229', cost:9e+149,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade230', cost:5e+150,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade231', cost:2e+151,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade232', cost:8e+151,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade233', cost:2.4e+152,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade234', cost:7.2e+152,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade235', cost:2.1e+154,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade236', cost:5e+155,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:4.44444444444 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade237', cost:7.77e+155, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade238', cost:8.88e+155, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade239', cost:9.99e+155, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade240', cost:2e+156,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade241', cost:4e+156,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade242', cost:8e+156,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade243', cost:1.6e+157,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade244', cost:3.2e+157,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade245', cost:6.4e+157,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade246', cost:1.28e+158, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade247', cost:5.14e+158, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2.99792458 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade248', cost:1e+159,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade249', cost:1e+160,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade250', cost:2.5e+160,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade251', cost:5e+160,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade252', cost:7.5e+160,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade253', cost:1e+161,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade254', cost:1.5e+161,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade255', cost:2e+161,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade256', cost:3e+161,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade257', cost:4e+161,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade258', cost:9e+161,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2.35711 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade259', cost:1e+162,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:24 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade260', cost:2.5e+164,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade261', cost:5e+164,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:22 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade262', cost:7.5e+164,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade263', cost:1e+165,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:20 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade264', cost:2.5e+167,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade265', cost:5e+167,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:18 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade266', cost:7.5e+167,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade267', cost:1e+168,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:16 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade268', cost:2.5e+170,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade269', cost:5e+170,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:14 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade270', cost:7.5e+170,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade271', cost:1e+171,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:12 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade272', cost:2.5e+173,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade273', cost:5e+173,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:10 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade274', cost:7.5e+173,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade275', cost:1e+174,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:8 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade276', cost:2.5e+176,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade277', cost:5e+176,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:4 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade278', cost:1e+177,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade279', cost:5e+183,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:9.87654321 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade280', cost:5e+189,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade281', cost:2.7e+193,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade282', cost:1.3e+196,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:4 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade283', cost:2e+198,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade284', cost:1e+201,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade285', cost:1.4e+202,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade286', cost:9.6e+202,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade287', cost:1.98e+203, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade288', cost:3.22e+203, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade289', cost:6.79e+203, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade290', cost:8.88e+203, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade291', cost:1.9e+205,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade292', cost:8.1e+205,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade293', cost:1.99e+206, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade294', cost:2.33e+206, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade295', cost:4.21e+206, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade296', cost:6.07e+206, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade297', cost:7.77e+206, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade298', cost:9.1e+206,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade299', cost:1e+207,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:2.1 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade300', cost:2e+207,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade301', cost:9e+207,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade302', cost:4.5e+208,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade303', cost:2e+209,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade304', cost:3.28e+209, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade305', cost:6e+209,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade306', cost:1e+213,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:1.5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade307', cost:1e+214,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:11 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade308', cost:1e+214,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:11 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade309', cost:1e+214,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:11 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade310', cost:1e+214,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:11 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade311', cost:1e+214,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:11 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade312', cost:1e+214,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:11 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade313', cost:1e+214,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:11 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade314', cost:1e+214,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:11 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade315', cost:1e+214,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:11 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade316', cost:1e+214,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:11 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade317', cost:1.5e+215,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade318', cost:1.66e+215, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade319', cost:1.93e+215, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade320', cost:4.1e+215,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade321', cost:6.78e+215, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade322', cost:9e+215,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade323', cost:1e+216,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:1 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade324', cost:1.2e+217,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade325', cost:6.7e+217,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade326', cost:1.23e+218, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade327', cost:3.21e+218, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade328', cost:5.55e+218, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade329', cost:8e+218,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade330', cost:8e+218,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade331', cost:8e+218,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade332', cost:9e+218,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade333', cost:1e+219,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade334', cost:3e+219,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade335', cost:4e+219,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade336', cost:5e+219,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade337', cost:6e+219,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade338', cost:3e+221,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade339', cost:4.21e+221, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade340', cost:6e+221,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade341', cost:7.89e+221, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade342', cost:8.45e+221, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade343', cost:1e+222,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:0.5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade344', cost:2e+222,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade345', cost:5e+222,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade346', cost:1.4e+223,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade347', cost:5.4e+223,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade348', cost:1.08e+224, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade349', cost:2.19e+224, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade350', cost:4.68e+224, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade351', cost:1e+225,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade352', cost:1e+228,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:1.2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade353', cost:1e+228,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade354', cost:1e+228,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade355', cost:1e+228,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade356', cost:1e+228,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade357', cost:1e+228,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade358', cost:1e+228,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade359', cost:1e+228,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade360', cost:1e+228,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade361', cost:1e+228,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade362', cost:1e+228,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade363', cost:1e+230,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade364', cost:1e+231,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:1.3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade365', cost:3e+231,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade366', cost:8e+231,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade367', cost:1e+232,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:0.7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade368', cost:6.9e+232,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade369', cost:1e+233,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade370', cost:1.88e+233, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade371', cost:2.39e+233, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade372', cost:4.11e+233, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade373', cost:7e+233,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade374', cost:9.12e+233, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade375', cost:1.2e+235,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade376', cost:2.4e+235,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade377', cost:6.3e+235,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade378', cost:1.99e+236, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade379', cost:3.98e+236, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade380', cost:5.66e+236, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade381', cost:7e+236,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade382', cost:8e+236,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade383', cost:9e+236,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade384', cost:1e+237,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade385', cost:1e+238,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:4 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade386', cost:1.2e+238,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade387', cost:2.5e+238,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade388', cost:5e+238,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade389', cost:1e+240,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:0.3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade390', cost:1e+240,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade391', cost:5e+240,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade392', cost:9e+240,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade393', cost:1e+241,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade394', cost:2.1e+241,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade395', cost:4.5e+241,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade396', cost:8.9e+241,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade397', cost:1.53e+242, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade398', cost:2.99e+242, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade399', cost:5.77e+242, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade400', cost:8.13e+242, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade401', cost:1e+243,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:1 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade402', cost:2e+243,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade403', cost:1e+244,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:6 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade404', cost:2.2e+244,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade405', cost:4.4e+244,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade406', cost:6.6e+244,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade407', cost:8.8e+244,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade408', cost:1.11e+245, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade409', cost:2.22e+245, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade410', cost:3.33e+245, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade411', cost:4.44e+245, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade412', cost:5.55e+245, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade413', cost:1e+246,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:1.5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade414', cost:1e+247,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:4 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade415', cost:1e+249,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:0.9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade416', cost:1e+250,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade417', cost:1e+252,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:0.6 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade418', cost:1e+252,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade419', cost:1e+253,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade420', cost:1e+253,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade421', cost:1e+253,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade422', cost:1e+253,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade423', cost:1e+253,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade424', cost:1e+253,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade425', cost:1e+253,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade426', cost:1e+253,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade427', cost:1e+253,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade428', cost:1e+253,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade429', cost:1e+253,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade430', cost:5e+253,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade431', cost:7.5e+253,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade432', cost:1.25e+254, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade433', cost:6.25e+254, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade434', cost:1e+255,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:1 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade435', cost:3e+255,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade436', cost:1e+256,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:6 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade437', cost:1.5e+256,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade438', cost:7.5e+256,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade439', cost:3.75e+257, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade440', cost:1e+258,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade441', cost:8e+257,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade442', cost:1e+258,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:1.1 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade443', cost:2.5e+258,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade444', cost:6.4e+258,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade445', cost:1e+259,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade446', cost:1.22e+259, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade447', cost:2.33e+260, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade448', cost:3.99e+260, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade449', cost:7.66e+260, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade450', cost:1e+261,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:0.9 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade451', cost:1e+261,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade452', cost:1e+262,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade453', cost:1.9e+262,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade454', cost:9.8e+262,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade455', cost:2.6e+263,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade456', cost:5.44e+263, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade457', cost:7e+263,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade458', cost:1e+264,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:2 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade459', cost:1e+264,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade460', cost:1e+265,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade461', cost:4.5e+265,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade462', cost:6.9e+265,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade463', cost:8.9e+265,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade464', cost:1.89e+266, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade465', cost:2.89e+266, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade466', cost:4.48e+266, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade467', cost:9e+266,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade468', cost:1e+267,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade469', cost:5e+267,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:3 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade470', cost:1e+268,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade471', cost:1e+270,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:4 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade472', cost:1e+270,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade473', cost:1e+273,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:1 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade474', cost:1e+273,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade475', cost:2e+273,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade476', cost:3e+273,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade477', cost:6e+273,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade478', cost:2.5e+274,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade479', cost:2e+275,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade480', cost:6e+275,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade481', cost:9.99e+275, count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade482', cost:1e+276,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade483', cost:1e+277,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:4 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade484', cost:1.5e+277,  count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade485', cost:3e+277,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:7 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade486', cost:1e+279,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:2.1 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade487', cost:1e+280,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade488', cost:1e+282,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:4 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade489', cost:1e+283,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:7.77 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade490', cost:1e+285,    count:0, canBuy:false, modifier:{ type:'darkmatter', galaxyId:'galaxy0', coeff:5 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade491', cost:1e+285,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT1' ], coeff:13 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade492', cost:1e+285,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT2' ], coeff:13 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade493', cost:1e+285,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT3' ], coeff:13 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade494', cost:1e+285,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT4' ], coeff:13 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade495', cost:1e+285,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT5' ], coeff:13 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade496', cost:1e+285,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT6' ], coeff:13 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade497', cost:1e+285,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT7' ], coeff:13 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade498', cost:1e+285,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT8' ], coeff:13 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade499', cost:1e+285,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT9' ], coeff:13 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade500', cost:1e+286,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:7.77 } },
        { galaxyId:'galaxy0', id:'galaxy0upgrade501', cost:1e+288,    count:0, canBuy:false, modifier:{ type:'damage', shipIds:[ 'galaxy0shipT0', 'galaxy0shipT1', 'galaxy0shipT2', 'galaxy0shipT3', 'galaxy0shipT4', 'galaxy0shipT5', 'galaxy0shipT6', 'galaxy0shipT7', 'galaxy0shipT8', 'galaxy0shipT9' ], coeff:77.77 } },
    ],
}

export const state = () => ({
    ...initialState
})

export const getters = {
    
    saveData:(state) => (galaxyId) => {
        
        let upgrades = state.upgrades.filter(upgrade => upgrade.galaxyId == galaxyId && upgrade.count != 0)
        
        let data = []
        upgrades.forEach(upgrade => {
            
            data.push(upgrade.id)
        })
        
        return data
    },
    
    purchasedList: (state) => {
        
        return state.upgrades.filter(upgrade => upgrade.count > 0)
    },    
    
    purchasedListByGalaxy: (state) => (galaxyId) => {
        
        return state.upgrades.filter(upgrade => upgrade.galaxyId === galaxyId && upgrade.count > 0)
    },
    
    currentListByGalaxy: (state) => (galaxyId) => {
        
        return state.upgrades.filter(upgrade => upgrade.galaxyId === galaxyId && upgrade.count <= 0)
    },
}

export const actions = {
    
    load({ state, commit }, payload) {
        
        payload.data.forEach(upgradeId => {
            
            commit('setCount', { upgradeId:upgradeId, value:1 })
        })
    },
}

export const mutations = {
    
    reset(state, payload) {
        
        let upgrades = state.upgrades.filter(upgrade => upgrade.galaxyId == payload.galaxyId)
        upgrades.forEach(upgrade => {
            
            upgrade.count = 0
        })
    },
    
    setCount(state, payload) {
        
        let upgrade = state.upgrades.find(upgrade => upgrade.id === payload.upgradeId)
        upgrade.count = payload.value
    },
    
    setCanBuy(state, payload) {
        
        let upgrade = state.upgrades.find(upgrade => upgrade.id === payload.upgradeId)
        upgrade.canBuy = payload.value
    },
}